unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ExtCtrls, StdCtrls, TrCtrls, Buttons;

type
  TForm1 = class(TForm)
    Image1: TImage;
    TrRadioGroup1: TTrRadioGroup;
    TrRadioButton1: TTrRadioButton;
    TrCheckBox1: TTrCheckBox;
    TrGroupBox1: TTrGroupBox;
    TrRadioButton5: TTrRadioButton;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.DFM}




end.
