//---------------------------------------------------------------------------
#include <vcl\condefs.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "DiffUnit.hpp"

#pragma hdrstop
//---------------------------------------------------------------------------
USERES("Diff.res");
USEUNIT("DiffUnit.pas");
//---------------------------------------------------------------------------
int main(int argc, char **argv)
{
 MainProc();
 return 0;
}
//---------------------------------------------------------------------------
